name: Deploy Infraestructure with Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      # Github token
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Terraform
      TERRAFORM_VERSION: '0.12.24'
      TERRAFORM_WORKDIR: './terraform'

      # AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKDIR }}

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKDIR }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKDIR }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKDIR }}

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKDIR }}
  
  dispatch:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-app